apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6nnq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0051-tenant/tkrw-pr712-0075-0051-app/devfile-sample-6nnq@sha256:671666a81eb5147a9326eafbd96d5a63f8aee3adccd8b394ec937df728d1fb51
        name: my-nodejs
        resources: {}
status: {}
